### ISSUE TITLE
How do I manage errors that arise from when I attempt to start the localhost?

### ISSUE THREAD

**Issue by chilu18** [bongohive-internship/rest-api-express-node-chilu18#1]
After having successfully followed all instructions leading up to this point which is, initialized npm and created a JSON package file I am still facing a challenge that permits from going any further with this exercise, how would you recommend I go about managing these errors? (screenshot attached)
 
![image](https://user-images.githubusercontent.com/7957943/59504671-bb9db880-8ea3-11e9-92ba-a8181683e88b.png)

**Comment by Joebbrien** [comment]
Hi @chilu18 thanks for raising this issue

I have seen the error, check the resources and read up more on starting a Node JS server.
This should be your challenge to solve.

Thanks
